services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: board
      MYSQL_PASSWORD: board
      MYSQL_DATABASE: board
    ports:
      - "3307:3306"

